version: "3.7"

services:

  flask:
    build: ./flask
    env_file: 
      - flask.env
    container_name: flask
    restart: always
    volumes:
      - flask-resources:/app/webapp/static/resources
      - reqlog:/tmp/reqlog
      - errlog:/tmp/errlog
    expose:
      - 8080

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: asdasdasd
      POSTGRES_USER: daniel2
      POSTGRES_DB: my_db2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 127.0.0.1:8081:8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-errors:/var/log/nginx


volumes:
  postgres-data:
    driver: local
  reqlog:
    driver: local
  errlog:
    driver: local
  flask-resources:
    driver: local
  nginx-errors:
    driver: local
